// packages/vue/src/components/Divider/Divider.vue
<script lang="ts">
export type DividerOrientation = 'horizontal' | 'vertical';
</script>

<script setup lang="ts">
import { computed, useSlots } from 'vue';
import { cx } from '../../utils/cx';

/**
 * Divider — a separator rule. Horizontal by default; can be vertical (inside a
 * flex row) or carry a centered label (default slot).
 *
 * @example
 * ```vue
 * <Divider />
 * <Divider>または</Divider>
 * <Divider orientation="vertical" />
 * ```
 */
const props = withDefaults(
  defineProps<{
    /** Orientation. */
    orientation?: DividerOrientation;
    /** Use the stronger border color. */
    strong?: boolean;
    /** Horizontal alignment of the label, if any. */
    align?: 'start' | 'center' | 'end';
  }>(),
  { orientation: 'horizontal', strong: false, align: 'center' },
);

const slots = useSlots();
const labeled = computed(() => !!slots.default && props.orientation === 'horizontal');

const classes = computed(() =>
  cx(
    'lily-divider',
    props.orientation === 'vertical' && 'lily-divider--vertical',
    props.strong && 'lily-divider--strong',
    labeled.value && 'lily-divider--labeled',
    labeled.value && props.align !== 'center' && `lily-divider--${props.align}`,
  ),
);
</script>

<template>
  <div
    :class="classes"
    role="separator"
    :aria-orientation="orientation === 'vertical' ? 'vertical' : undefined"
  >
    <span v-if="labeled"><slot /></span>
  </div>
</template>

// packages/react/src/components/Divider/Divider.tsx
import { forwardRef } from 'react';
import type { HTMLAttributes, ReactNode } from 'react';
import { cx } from '../../utils/cx';

export type DividerOrientation = 'horizontal' | 'vertical';

export interface DividerProps extends HTMLAttributes<HTMLDivElement> {
  /** Orientation. @default 'horizontal' */
  orientation?: DividerOrientation;
  /** Use the stronger border color. @default false */
  strong?: boolean;
  /** Horizontal alignment of the label, if any. @default 'center' */
  align?: 'start' | 'center' | 'end';
  /** Optional centered label (horizontal only). */
  children?: ReactNode;
}

/**
 * Divider — a separator rule. Horizontal by default; can be vertical (for use
 * inside a flex row) or carry a centered label.
 *
 * @example
 * ```tsx
 * <Divider />
 * <Divider>または</Divider>
 * <Divider orientation="vertical" />
 * ```
 */
export const Divider = forwardRef<HTMLDivElement, DividerProps>(function Divider(
  { orientation = 'horizontal', strong = false, align = 'center', className, children, ...rest },
  ref,
) {
  const labeled = children != null && orientation === 'horizontal';
  const classes = cx(
    'lily-divider',
    orientation === 'vertical' && 'lily-divider--vertical',
    strong && 'lily-divider--strong',
    labeled && 'lily-divider--labeled',
    labeled && align !== 'center' && `lily-divider--${align}`,
    className,
  );

  return (
    <div
      ref={ref}
      className={classes}
      role="separator"
      aria-orientation={orientation === 'vertical' ? 'vertical' : undefined}
      {...rest}
    >
      {labeled ? <span>{children}</span> : null}
    </div>
  );
});
