// packages/react/src/components/Presence/Presence.tsx
import { cloneElement, isValidElement, type ReactElement, type Ref } from 'react';
import { cx } from '../../utils/cx';
import { mergeRefs } from '../../utils/mergeRefs';
import { usePresence } from '../../hooks/usePresence';
import type { AnimationName } from '../../motion/animations';

export interface PresenceProps {
  /** Whether the child should be shown. Exit animation plays when it goes false. */
  present: boolean;
  /** Entrance animation (catalog name). @default 'fade-in' */
  enter?: AnimationName;
  /** Exit animation (catalog name). @default 'fade-out' */
  exit?: AnimationName;
  /**
   * The single element to animate. It must accept `className`, `style`, and a
   * forwarded `ref` (every Lily component does).
   */
  children: ReactElement;
}

/**
 * Animate a single child in and out of the DOM using the animation catalog.
 *
 * Keeps the child mounted through its exit animation, then removes it. Honors
 * the motion tier (`minimal` shortens to a fade, `none`/reduced-motion unmounts
 * instantly).
 *
 * @example
 * <Presence present={open} enter="zoom-in" exit="zoom-out">
 *   <div className="card">…</div>
 * </Presence>
 */
export function Presence({ present, enter = 'fade-in', exit = 'fade-out', children }: PresenceProps) {
  const { isPresent, state, ref } = usePresence(present);

  if (!isPresent || !isValidElement(children)) return null;

  // While leaving, present is already false → play the exit animation.
  const name = present ? enter : exit;
  const child = children as ReactElement<{
    className?: string;
    'data-state'?: string;
    ref?: Ref<HTMLElement>;
  }>;
  const childRef = (child as { ref?: Ref<HTMLElement> }).ref;

  return cloneElement(child, {
    className: cx('lily-animate', `lily-animate--${name}`, child.props.className),
    'data-state': state,
    ref: childRef ? mergeRefs(childRef, ref) : ref,
  });
}

// packages/vue/src/components/Presence/Presence.vue
<script lang="ts">
import { defineComponent, cloneVNode, toRef, type PropType, type VNode } from 'vue';
import { usePresence } from '../../composables/presence';
import type { AnimationName } from '../../composables/animations';

/**
 * Presence — animate a single slotted element in and out of the DOM using the
 * animation catalog. Keeps it mounted through the exit animation, then removes
 * it. Honors the motion tier. The Vue mirror of the React `<Presence>`.
 *
 * @example
 * ```vue
 * <Presence :present="open" enter="zoom-in" exit="zoom-out">
 *   <div class="card">…</div>
 * </Presence>
 * ```
 */
export default defineComponent({
  name: 'LilyPresence',
  props: {
    /** Whether the child should be shown. Exit plays when it goes false. */
    present: { type: Boolean, required: true },
    /** Entrance animation (catalog name). */
    enter: { type: String as PropType<AnimationName>, default: 'fade-in' },
    /** Exit animation (catalog name). */
    exit: { type: String as PropType<AnimationName>, default: 'fade-out' },
  },
  setup(props, { slots }) {
    const present = toRef(props, 'present');
    const { isPresent, state, node } = usePresence(present);

    return () => {
      if (!isPresent.value) return null;
      const children = slots.default?.();
      const vnode = children?.[0];
      if (!vnode) return null;
      // While leaving, present is already false → play the exit animation.
      const name = props.present ? props.enter : props.exit;
      return cloneVNode(vnode as VNode, {
        class: ['lily-animate', `lily-animate--${name}`],
        'data-state': state.value,
        ref: node,
      });
    };
  },
});
</script>
