// packages/vue/src/components/NumberInput/NumberInput.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cx } from '../../utils/cx';

/**
 * NumberInput — a numeric field with stepper buttons. Bind with `v-model`
 * (value is `null` when empty). The native input keeps spinbutton semantics.
 *
 * @example
 * ```vue
 * <NumberInput v-model="qty" :min="0" :max="99" aria-label="数量" />
 * ```
 */
const props = withDefaults(
  defineProps<{
    min?: number;
    max?: number;
    step?: number;
    size?: 'sm' | 'md' | 'lg';
    disabled?: boolean;
    id?: string;
    ariaLabel?: string;
    decrementLabel?: string;
    incrementLabel?: string;
  }>(),
  { step: 1, size: 'md', disabled: false, decrementLabel: 'Decrease', incrementLabel: 'Increase' },
);

const model = defineModel<number | null>({ default: null });

function clamp(n: number): number {
  if (props.min != null && n < props.min) return props.min;
  if (props.max != null && n > props.max) return props.max;
  return n;
}

const base = computed(() => model.value ?? props.min ?? 0);
const atMin = computed(() => props.min != null && model.value != null && model.value <= props.min);
const atMax = computed(() => props.max != null && model.value != null && model.value >= props.max);
const classes = computed(() => cx('lily-number-input', props.size !== 'md' && `lily-number-input--${props.size}`));

function onInput(e: Event): void {
  const raw = (e.target as HTMLInputElement).value;
  model.value = raw === '' ? null : clamp(Number(raw));
}
</script>

<template>
  <div :class="classes">
    <button
      type="button"
      class="lily-number-input__btn"
      :aria-label="decrementLabel"
      :disabled="disabled || atMin"
      @click="model = clamp(base - step)"
    >
      <span aria-hidden="true">−</span>
    </button>
    <input
      :id="id"
      type="number"
      class="lily-number-input__field"
      inputmode="decimal"
      :aria-label="ariaLabel"
      :value="model ?? ''"
      :min="min"
      :max="max"
      :step="step"
      :disabled="disabled"
      @input="onInput"
    />
    <button
      type="button"
      class="lily-number-input__btn"
      :aria-label="incrementLabel"
      :disabled="disabled || atMax"
      @click="model = clamp(base + step)"
    >
      <span aria-hidden="true">+</span>
    </button>
  </div>
</template>

// packages/react/src/components/NumberInput/NumberInput.tsx
import { forwardRef, type InputHTMLAttributes } from 'react';
import { cx } from '../../utils/cx';
import { useControllableState } from '../../hooks';
import { useFieldControl } from '../FormField';

export interface NumberInputProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'value' | 'defaultValue' | 'onChange' | 'size' | 'type'> {
  /** Controlled value (`null` when empty). */
  value?: number | null;
  /** Initial value when uncontrolled. */
  defaultValue?: number | null;
  /** Called with the new value (`null` when cleared). */
  onChange?: (value: number | null) => void;
  /** Minimum value. */
  min?: number;
  /** Maximum value. */
  max?: number;
  /** Step for the buttons and keyboard. @default 1 */
  step?: number;
  /** Control size. @default 'md' */
  size?: 'sm' | 'md' | 'lg';
  /** Accessible label for the decrement button. @default 'Decrease' */
  decrementLabel?: string;
  /** Accessible label for the increment button. @default 'Increase' */
  incrementLabel?: string;
}

function clamp(n: number, min?: number, max?: number): number {
  if (min != null && n < min) return min;
  if (max != null && n > max) return max;
  return n;
}

/**
 * NumberInput — a numeric field with stepper buttons. The native input keeps
 * spinbutton semantics (Up/Down arrows), and the buttons add a pointer
 * affordance. Inherits FormField wiring when nested in one.
 *
 * @example
 * ```tsx
 * <FormField label="数量"><NumberInput min={0} max={99} defaultValue={1} /></FormField>
 * ```
 */
export const NumberInput = forwardRef<HTMLInputElement, NumberInputProps>(function NumberInput(
  { value: valueProp, defaultValue = null, onChange, min, max, step = 1, size = 'md', decrementLabel = 'Decrease', incrementLabel = 'Increase', className, disabled, ...rest },
  ref,
) {
  const [value, setValue] = useControllableState<number | null>({
    value: valueProp,
    defaultValue,
    onChange,
  });
  const fieldProps = useFieldControl(rest);

  const base = value ?? min ?? 0;
  const atMin = min != null && value != null && value <= min;
  const atMax = max != null && value != null && value >= max;

  return (
    <div className={cx('lily-number-input', size !== 'md' && `lily-number-input--${size}`, className)}>
      <button
        type="button"
        className="lily-number-input__btn"
        aria-label={decrementLabel}
        disabled={disabled || atMin}
        onClick={() => setValue(clamp(base - step, min, max))}
      >
        <span aria-hidden="true">−</span>
      </button>
      <input
        ref={ref}
        type="number"
        className="lily-number-input__field"
        inputMode="decimal"
        value={value ?? ''}
        min={min}
        max={max}
        step={step}
        disabled={disabled}
        onChange={(e) => {
          const raw = e.target.value;
          setValue(raw === '' ? null : clamp(Number(raw), min, max));
        }}
        {...fieldProps}
      />
      <button
        type="button"
        className="lily-number-input__btn"
        aria-label={incrementLabel}
        disabled={disabled || atMax}
        onClick={() => setValue(clamp(base + step, min, max))}
      >
        <span aria-hidden="true">+</span>
      </button>
    </div>
  );
});
