// packages/vue/src/components/Calendar/Calendar.vue
<script lang="ts">
import type { Weekday } from '../DatePicker/DatePicker.vue';
export type { Weekday };
</script>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { cx } from '../../utils/cx';
import { getDateTimeFormat, today, toPlainDate, toUtcDate, type PlainDateInput } from '../../utils/datetime';

/**
 * Calendar — an inline month grid for date selection. Bind with `v-model`.
 *
 * @example
 * ```vue
 * <Calendar v-model="date" locale="ja-JP" />
 * ```
 */
const props = withDefaults(
  defineProps<{
    min?: PlainDateInput;
    max?: PlainDateInput;
    isDateDisabled?: (d: Temporal.PlainDate) => boolean;
    locale?: Intl.LocalesArgument;
    weekStartsOn?: Weekday;
    label?: string;
  }>(),
  { weekStartsOn: 1 },
);

const model = defineModel<Temporal.PlainDate | null>({ default: null });
const view = ref((model.value ?? today()).with({ day: 1 }));

// An unparsable bound is treated as "no bound" rather than throwing during render.
const toBound = (input: PlainDateInput | undefined): Temporal.PlainDate | undefined => {
  if (input == null) return undefined;
  try {
    return toPlainDate(input);
  } catch {
    return undefined;
  }
};
const minD = computed(() => toBound(props.min));
const maxD = computed(() => toBound(props.max));
const fmt = (d: Temporal.PlainDate, opts: Intl.DateTimeFormatOptions) =>
  getDateTimeFormat(props.locale, { timeZone: 'UTC', ...opts }).format(toUtcDate(d.year, d.month, d.day));

const gridStart = computed(() => view.value.subtract({ days: (view.value.dayOfWeek - props.weekStartsOn + 7) % 7 }));
const days = computed(() => Array.from({ length: 42 }, (_, i) => gridStart.value.add({ days: i })));
const weekdays = computed(() => Array.from({ length: 7 }, (_, i) => fmt(gridStart.value.add({ days: i }), { weekday: 'short' })));

function disabled(d: Temporal.PlainDate): boolean {
  return (
    (!!minD.value && Temporal.PlainDate.compare(d, minD.value) < 0) ||
    (!!maxD.value && Temporal.PlainDate.compare(d, maxD.value) > 0) ||
    (props.isDateDisabled?.(d) ?? false)
  );
}
function select(d: Temporal.PlainDate): void {
  model.value = d;
  if (d.month !== view.value.month) view.value = d.with({ day: 1 });
}
function isToday(d: Temporal.PlainDate): boolean {
  return d.equals(today());
}
</script>

<template>
  <div :class="cx('lily-calendar')">
    <div class="lily-calendar__header">
      <button type="button" class="lily-calendar__nav" aria-label="前の月" @click="view = view.subtract({ months: 1 })">
        <span aria-hidden="true">‹</span>
      </button>
      <span class="lily-calendar__title" aria-live="polite">{{ fmt(view, { year: 'numeric', month: 'long' }) }}</span>
      <button type="button" class="lily-calendar__nav" aria-label="次の月" @click="view = view.add({ months: 1 })">
        <span aria-hidden="true">›</span>
      </button>
    </div>
    <div class="lily-calendar__grid" role="group" :aria-label="label ?? 'Calendar'">
      <span v-for="(wd, i) in weekdays" :key="i" class="lily-calendar__weekday" aria-hidden="true">{{ wd }}</span>
      <button
        v-for="d in days"
        :key="d.toString()"
        type="button"
        :class="cx('lily-calendar__day', d.month !== view.month && 'lily-calendar__day--outside', isToday(d) && 'lily-calendar__day--today')"
        :aria-pressed="model != null && d.equals(model)"
        :aria-label="fmt(d, { year: 'numeric', month: 'long', day: 'numeric' })"
        :disabled="disabled(d)"
        @click="select(d)"
      >
        {{ d.day }}
      </button>
    </div>
  </div>
</template>

// packages/react/src/components/Calendar/Calendar.tsx
import { forwardRef, useState } from 'react';
import { cx } from '../../utils/cx';
import { useControllableState } from '../../hooks';
import { getDateTimeFormat, today, toPlainDate, toUtcDate, type PlainDateInput } from '../../utils/datetime';
import type { Weekday } from '../DatePicker';

export interface CalendarProps {
  /** Selected date (controlled). */
  value?: Temporal.PlainDate | null;
  /** Initial selection (uncontrolled). @default null */
  defaultValue?: Temporal.PlainDate | null;
  /** Called with the newly selected date. */
  onChange?: (date: Temporal.PlainDate) => void;
  /** Earliest selectable date. */
  min?: PlainDateInput;
  /** Latest selectable date. */
  max?: PlainDateInput;
  /** Disable individual dates. */
  isDateDisabled?: (date: Temporal.PlainDate) => boolean;
  /** Locale for month/weekday names. */
  locale?: Intl.LocalesArgument;
  /** Which weekday the grid starts on. @default 1 (Monday) */
  weekStartsOn?: Weekday;
  /** Accessible label for the grid. @default 'Calendar' */
  'aria-label'?: string;
  className?: string;
}

const toDate = (d: Temporal.PlainDate) => toUtcDate(d.year, d.month, d.day);
// Formatters are cached per locale + options (a grid formats ~50 labels per render).
const fmt = (d: Temporal.PlainDate, locale: Intl.LocalesArgument, opts: Intl.DateTimeFormatOptions) =>
  getDateTimeFormat(locale, { timeZone: 'UTC', ...opts }).format(toDate(d));

/**
 * Coerce an optional `PlainDateInput` to a `PlainDate` (or `undefined`).
 * Bounds are parsed defensively: an invalid ISO string is ignored (no bound)
 * instead of throwing during render.
 */
function toBound(input: PlainDateInput | undefined): Temporal.PlainDate | undefined {
  if (input == null) return undefined;
  try {
    return toPlainDate(input);
  } catch {
    return undefined;
  }
}

/**
 * Calendar — an inline month grid for date selection (a DatePicker without the
 * popup). Days are buttons; the selection is conveyed by fill + `aria-pressed`.
 *
 * @example
 * ```tsx
 * <Calendar defaultValue={today()} onChange={setDate} locale="ja-JP" />
 * ```
 */
export const Calendar = forwardRef<HTMLDivElement, CalendarProps>(function Calendar(
  { value: valueProp, defaultValue = null, onChange, min, max, isDateDisabled, locale, weekStartsOn = 1, className, ...rest },
  ref,
) {
  const [selected, setSelected] = useControllableState<Temporal.PlainDate | null>({
    value: valueProp,
    defaultValue,
    onChange: (v) => v && onChange?.(v),
  });
  const [view, setView] = useState(() => (selected ?? today()).with({ day: 1 }));
  const minD = toBound(min);
  const maxD = toBound(max);

  // Resolved once per render instead of once per day cell.
  const todayDate = today();

  const firstOffset = (view.dayOfWeek - weekStartsOn + 7) % 7;
  const gridStart = view.subtract({ days: firstOffset });
  const days = Array.from({ length: 42 }, (_, i) => gridStart.add({ days: i }));
  const weekdays = Array.from({ length: 7 }, (_, i) => fmt(gridStart.add({ days: i }), locale, { weekday: 'short' }));

  const disabled = (d: Temporal.PlainDate) =>
    (minD && Temporal.PlainDate.compare(d, minD) < 0) ||
    (maxD && Temporal.PlainDate.compare(d, maxD) > 0) ||
    (isDateDisabled?.(d) ?? false);

  return (
    <div ref={ref} className={cx('lily-calendar', className)} {...rest}>
      <div className="lily-calendar__header">
        <button type="button" className="lily-calendar__nav" aria-label="前の月" onClick={() => setView(view.subtract({ months: 1 }))}>
          <span aria-hidden="true">‹</span>
        </button>
        <span className="lily-calendar__title" aria-live="polite">
          {fmt(view, locale, { year: 'numeric', month: 'long' })}
        </span>
        <button type="button" className="lily-calendar__nav" aria-label="次の月" onClick={() => setView(view.add({ months: 1 }))}>
          <span aria-hidden="true">›</span>
        </button>
      </div>
      <div className="lily-calendar__grid" role="group" aria-label={rest['aria-label'] ?? 'Calendar'}>
        {weekdays.map((wd, i) => (
          <span key={i} className="lily-calendar__weekday" aria-hidden="true">
            {wd}
          </span>
        ))}
        {days.map((d) => {
          const outside = d.month !== view.month;
          const isSelected = selected != null && d.equals(selected);
          return (
            <button
              key={d.toString()}
              type="button"
              className={cx('lily-calendar__day', outside && 'lily-calendar__day--outside', d.equals(todayDate) && 'lily-calendar__day--today')}
              aria-pressed={isSelected}
              aria-label={fmt(d, locale, { year: 'numeric', month: 'long', day: 'numeric' })}
              disabled={disabled(d)}
              onClick={() => {
                setSelected(d);
                if (outside) setView(d.with({ day: 1 }));
              }}
            >
              {d.day}
            </button>
          );
        })}
      </div>
    </div>
  );
});
