// packages/vue/src/components/Grid/Col.vue
<script lang="ts">
/** A column span: 1–12, `'auto'` (content width), or `true` (equal width). */
export type ColSpan = number | 'auto' | boolean;

/** Per-breakpoint span configuration. */
export interface ColResponsive {
  sm?: ColSpan;
  md?: ColSpan;
  lg?: ColSpan;
  xl?: ColSpan;
  /** Span at the `2xl` breakpoint (prop name `xxl`; emits the `-2xl` class). */
  xxl?: ColSpan;
}
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { cx } from '../../utils/cx';

/**
 * Col — a column in the 12-column {@link Row} grid.
 *
 * @example
 * ```vue
 * <Col :span="12" :md="6" :lg="4">responsive column</Col>
 * <Col>equal width</Col>
 * <Col span="auto">content width</Col>
 * ```
 */
const props = withDefaults(
  defineProps<{
    /** Element/component to render as. */
    as?: string | object;
    /** Base (xs) span. */
    span?: ColSpan;
    /** Base (xs) offset, 0–11. */
    offset?: number;
    /** Span at `sm` breakpoint. */
    sm?: ColSpan;
    /** Span at `md` breakpoint. */
    md?: ColSpan;
    /** Span at `lg` breakpoint. */
    lg?: ColSpan;
    /** Span at `xl` breakpoint. */
    xl?: ColSpan;
    /** Span at the `2xl` breakpoint (emits the `-2xl` class). */
    xxl?: ColSpan;
  }>(),
  {},
);

const CLASS = 'lily-col';

function spanClass(value: ColSpan | undefined, infix: string): string | false {
  if (value === undefined || value === false) return false;
  if (value === true) return `${CLASS}${infix}`;
  return `${CLASS}${infix}-${value}`;
}

const classes = computed(() => {
  // Default to equal-width when no base span is given.
  const base = props.span === undefined && props.offset === undefined ? true : props.span;

  return cx(
    spanClass(base, ''),
    props.offset ? `lily-offset-${props.offset}` : false,
    spanClass(props.sm, '-sm'),
    spanClass(props.md, '-md'),
    spanClass(props.lg, '-lg'),
    spanClass(props.xl, '-xl'),
    spanClass(props.xxl, '-2xl'),
  );
});
</script>

<template>
  <component :is="as ?? 'div'" :class="classes">
    <slot />
  </component>
</template>

// packages/react/src/components/Grid/Col.tsx
import { forwardRef, type ElementType } from 'react';
import { cx } from '../../utils/cx';
import type { PolymorphicProps } from '../../utils/polymorphic';

/** A column span: 1–12, `'auto'` (content width), or `true` (equal width). */
export type ColSpan = number | 'auto' | boolean;

/** Per-breakpoint span configuration. */
export interface ColResponsive {
  sm?: ColSpan;
  md?: ColSpan;
  lg?: ColSpan;
  xl?: ColSpan;
  '2xl'?: ColSpan;
}

export interface ColOwnProps extends ColResponsive {
  /** Base (xs) span. */
  span?: ColSpan;
  /** Base (xs) offset, 0–11. */
  offset?: number;
}

const CLASS = 'lily-col';
const DEFAULT_TAG = 'div' as const;
const BREAKPOINTS = ['sm', 'md', 'lg', 'xl', '2xl'] as const;

/** Map a single span value to its class name for a given breakpoint infix. */
function spanClass(value: ColSpan | undefined, infix: string): string | false {
  if (value === undefined || value === false) return false;
  if (value === true) return `${CLASS}${infix}`;
  return `${CLASS}${infix}-${value}`;
}

/**
 * Col — a column in the 12-column {@link Row} grid.
 *
 * @example
 * ```tsx
 * <Col span={12} md={6} lg={4}>responsive column</Col>
 * <Col>equal width</Col>
 * <Col span="auto">content width</Col>
 * ```
 */
function ColImpl<C extends ElementType = typeof DEFAULT_TAG>(
  {
    as,
    span,
    offset,
    sm,
    md,
    lg,
    xl,
    '2xl': xxl,
    className,
    children,
    ...rest
  }: PolymorphicProps<C, ColOwnProps> & { className?: string },
  ref: React.Ref<Element>,
) {
  const Tag = (as ?? DEFAULT_TAG) as ElementType;
  const responsive: ColResponsive = { sm, md, lg, xl, '2xl': xxl };

  // Default to equal-width when no base span is given.
  const base = span === undefined && offset === undefined ? true : span;

  const classes = cx(
    spanClass(base, ''),
    offset ? `lily-offset-${offset}` : false,
    ...BREAKPOINTS.map((bp) => spanClass(responsive[bp], `-${bp}`)),
    className,
  );

  return (
    <Tag ref={ref} className={classes} {...rest}>
      {children}
    </Tag>
  );
}

export const Col = forwardRef(ColImpl) as <C extends ElementType = typeof DEFAULT_TAG>(
  props: PolymorphicProps<C, ColOwnProps> & { className?: string; ref?: React.Ref<Element> },
) => React.ReactElement;
