// packages/vue/src/components/Offcanvas/Offcanvas.vue
<script lang="ts">
/** Edge the panel slides in from. */
export type OffcanvasPlacement = 'start' | 'end' | 'top' | 'bottom';
</script>

<script setup lang="ts">
import { computed, ref, useId, type ComponentPublicInstance } from 'vue';
import { cx } from '../../utils/cx';
import { useFocusTrap, useDismiss, useScrollLock } from '../../composables/interactions';
import { usePresence } from '../../composables/presence';
import type { AnimationName } from '../../composables/animations';
import CloseButton from '../CloseButton/CloseButton.vue';

/** Slide animation per edge — enter slides in from the edge, exit reverses. */
const ENTER_ANIM: Record<OffcanvasPlacement, AnimationName> = {
  start: 'slide-in-left',
  end: 'slide-in-right',
  top: 'slide-in-down',
  bottom: 'slide-in-up',
};
const EXIT_ANIM: Record<OffcanvasPlacement, AnimationName> = {
  start: 'slide-out-left',
  end: 'slide-out-right',
  top: 'slide-out-up',
  bottom: 'slide-out-down',
};

/**
 * Offcanvas — a panel that slides in from a screen edge, over a backdrop.
 *
 * Same accessibility model as {@link Modal}: dialog semantics, focus trap,
 * scroll lock, Escape/backdrop dismissal. Bind visibility with the `open` prop
 * and listen to `close`. Provide the title via the `title` prop or `#title`
 * slot and the body via the default slot.
 *
 * @example
 * ```vue
 * <Offcanvas :open="open" placement="end" title="Menu" @close="open = false">…</Offcanvas>
 * ```
 */
const props = withDefaults(
  defineProps<{
    /** Whether the panel is open. */
    open: boolean;
    /** Edge to slide in from. */
    placement?: OffcanvasPlacement;
    /** Panel title (accessible name). */
    title?: string;
  }>(),
  { placement: 'start' },
);

const emit = defineEmits<{ close: [] }>();
const slots = defineSlots<{
  default?: () => unknown;
  title?: () => unknown;
}>();

const CLASS = 'lily-offcanvas';
const titleId = useId();
const panelRef = ref<HTMLDivElement | null>(null);
const isOpen = computed(() => props.open);
const hasTitle = computed(() => !!props.title || !!slots.title);

const onClose = () => emit('close');

// Keep the panel mounted through its slide-out; the panel's animation end drives
// unmount (honors the motion tier automatically).
const { isPresent, state, node: presenceRef } = usePresence(isOpen);
const panelAnim = computed(() => (props.open ? ENTER_ANIM[props.placement] : EXIT_ANIM[props.placement]));
const backdropAnim = computed(() => (props.open ? 'fade-in' : 'fade-out'));

useFocusTrap(panelRef, isOpen);
useScrollLock(isOpen);
// Escape + backdrop (outside) click both dismiss, handled in one hook.
useDismiss(panelRef, isOpen, onClose, { outsideClick: true });

/** Bind both the panel template ref and the presence ref to the panel node. */
const setPanel = (el: Element | ComponentPublicInstance | null) => {
  panelRef.value = el instanceof HTMLDivElement ? el : null;
  presenceRef(el);
};
</script>

<template>
  <Teleport to="body">
    <div
      v-if="isPresent"
      :class="cx('lily-backdrop', 'lily-animate', `lily-animate--${backdropAnim}`, 'lily-animate--snappy')"
      :data-state="state"
    >
      <div
        :ref="setPanel"
        role="dialog"
        aria-modal="true"
        :aria-labelledby="hasTitle ? titleId : undefined"
        :data-state="state"
        :class="cx(CLASS, `${CLASS}--${placement}`, 'lily-animate', `lily-animate--${panelAnim}`, 'lily-animate--snappy')"
      >
        <div :class="`${CLASS}__header`">
          <h2 v-if="hasTitle" :id="titleId" :class="`${CLASS}__title`">
            <slot name="title">{{ title }}</slot>
          </h2>
          <CloseButton @click="onClose" />
        </div>
        <div :class="`${CLASS}__body`"><slot /></div>
      </div>
    </div>
  </Teleport>
</template>

// packages/react/src/components/Offcanvas/Offcanvas.tsx
import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { cx } from '../../utils/cx';
import { mergeRefs } from '../../utils/mergeRefs';
import { useFocusTrap, useDismiss, useScrollLock, usePresence } from '../../hooks';
import { CloseButton } from '../CloseButton';
import type { AnimationName } from '../../motion/animations';

export type OffcanvasPlacement = 'start' | 'end' | 'top' | 'bottom';

/** Slide animation per edge — enter slides in from the edge, exit reverses. */
const ENTER_ANIM: Record<OffcanvasPlacement, AnimationName> = {
  start: 'slide-in-left',
  end: 'slide-in-right',
  top: 'slide-in-down',
  bottom: 'slide-in-up',
};
const EXIT_ANIM: Record<OffcanvasPlacement, AnimationName> = {
  start: 'slide-out-left',
  end: 'slide-out-right',
  top: 'slide-out-up',
  bottom: 'slide-out-down',
};

export interface OffcanvasProps {
  /** Whether the panel is open. */
  open: boolean;
  /** Called when the panel requests to close. */
  onClose: () => void;
  /** Edge to slide in from. @default 'start' */
  placement?: OffcanvasPlacement;
  /** Panel title (accessible name). */
  title?: ReactNode;
  /** Body content. */
  children: ReactNode;
  className?: string;
}

const CLASS = 'lily-offcanvas';

/**
 * Offcanvas — a panel that slides in from a screen edge, over a backdrop.
 *
 * Same accessibility model as {@link Modal}: dialog semantics, focus trap,
 * scroll lock, Escape/backdrop dismissal.
 *
 * @example
 * ```tsx
 * <Offcanvas open={open} onClose={close} placement="end" title="Menu">…</Offcanvas>
 * ```
 */
export function Offcanvas({
  open,
  onClose,
  placement = 'start',
  title,
  children,
  className,
}: OffcanvasProps) {
  const panelRef = useRef<HTMLDivElement>(null);
  const titleId = useId();
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);

  // Keep the panel mounted through its slide-out; the panel's animation end
  // drives unmount (honors the motion tier automatically).
  const { isPresent, state, ref: presenceRef } = usePresence(open);

  useFocusTrap(panelRef, open);
  useScrollLock(open);
  // Escape + backdrop (outside) click both dismiss, handled in one hook.
  useDismiss(panelRef, open, onClose, { outsideClick: true });

  if (!mounted || !isPresent) return null;

  const panelAnim = open ? ENTER_ANIM[placement] : EXIT_ANIM[placement];

  return createPortal(
    <div
      className={cx('lily-backdrop', 'lily-animate', `lily-animate--${open ? 'fade-in' : 'fade-out'}`, 'lily-animate--snappy')}
      data-state={state}
    >
      <div
        ref={mergeRefs(panelRef, presenceRef)}
        role="dialog"
        aria-modal="true"
        aria-labelledby={title ? titleId : undefined}
        data-state={state}
        className={cx(CLASS, `${CLASS}--${placement}`, 'lily-animate', `lily-animate--${panelAnim}`, 'lily-animate--snappy', className)}
      >
        <div className={`${CLASS}__header`}>
          {title && (
            <h2 id={titleId} className={`${CLASS}__title`}>
              {title}
            </h2>
          )}
          <CloseButton onClick={onClose} />
        </div>
        <div className={`${CLASS}__body`}>{children}</div>
      </div>
    </div>,
    document.body,
  );
}
