// packages/vue/src/components/MonthPicker/MonthPicker.vue
<script lang="ts">
import { getDateTimeFormat, toUtcDate } from '../../utils/datetime';

/** Clamp `ym` into the inclusive `[min, max]` range. */
export function clampYearMonth(
  ym: Temporal.PlainYearMonth,
  min: Temporal.PlainYearMonth | undefined,
  max: Temporal.PlainYearMonth | undefined,
): Temporal.PlainYearMonth {
  if (min && Temporal.PlainYearMonth.compare(ym, min) < 0) return min;
  if (max && Temporal.PlainYearMonth.compare(ym, max) > 0) return max;
  return ym;
}

/** Localized month label via a fixed-UTC `Date`; the logic stays in Temporal. */
export function formatMonth(
  ym: Temporal.PlainYearMonth,
  locale: Intl.LocalesArgument,
  options: Intl.DateTimeFormatOptions,
): string {
  const utc = toUtcDate(ym.year, ym.month, 1);
  return getDateTimeFormat(locale, { timeZone: 'UTC', ...options }).format(utc);
}
</script>

<script setup lang="ts">
import { computed, nextTick, ref, useId, watch } from 'vue';
import { cx } from '../../utils/cx';
import { toPlainYearMonth, type PlainYearMonthInput } from '../../utils/datetime';
import { useDismiss } from '../../composables/interactions';

const CLASS = 'lily-month-picker';

/**
 * MonthPicker — pick a calendar month from a 12-month grid with prev/next year
 * navigation. The value is a `Temporal.PlainYearMonth`. Supports `v-model`.
 *
 * @example
 * ```vue
 * <MonthPicker v-model="month" />
 * ```
 */
const props = withDefaults(
  defineProps<{
    min?: PlainYearMonthInput;
    max?: PlainYearMonthInput;
    locale?: Intl.LocalesArgument;
    disabled?: boolean;
    size?: 'sm' | 'md' | 'lg';
    alignEnd?: boolean;
    toggleLabel?: string;
    id?: string;
  }>(),
  { disabled: false, size: 'md', alignEnd: false, toggleLabel: 'Choose month' },
);

/** Selected month; bind with `v-model`. Pass `null` for "no selection". */
const selected = defineModel<Temporal.PlainYearMonth | null>({ default: null });

const reactId = useId();
const baseId = computed(() => props.id ?? reactId);
const popupId = computed(() => `${baseId.value}-popup`);
const titleId = computed(() => `${baseId.value}-title`);

const rootRef = ref<HTMLDivElement | null>(null);
const toggleRef = ref<HTMLButtonElement | null>(null);
const gridRef = ref<HTMLDivElement | null>(null);
let focusCell = false;

const minYm = computed(() => toBound(props.min));
const maxYm = computed(() => toBound(props.max));

const nowYm = () => Temporal.Now.plainDateISO().toPlainYearMonth();

const open = ref(false);
const viewYear = ref<number>((selected.value ?? nowYm()).year);
const focused = ref<Temporal.PlainYearMonth>(
  selected.value ?? clampYearMonth(nowYm(), minYm.value, maxYm.value),
);

function toBound(input: PlainYearMonthInput | undefined): Temporal.PlainYearMonth | undefined {
  return input == null ? undefined : toPlainYearMonth(input);
}

function isSelectable(ym: Temporal.PlainYearMonth): boolean {
  if (minYm.value && Temporal.PlainYearMonth.compare(ym, minYm.value) < 0) return false;
  if (maxYm.value && Temporal.PlainYearMonth.compare(ym, maxYm.value) > 0) return false;
  return true;
}

function clampToBounds(ym: Temporal.PlainYearMonth): Temporal.PlainYearMonth {
  return clampYearMonth(ym, minYm.value, maxYm.value);
}

function moveFocus(ym: Temporal.PlainYearMonth) {
  const next = clampToBounds(ym);
  focusCell = true;
  focused.value = next;
  viewYear.value = next.year;
}

function openPopup() {
  if (props.disabled) return;
  const start = clampToBounds(selected.value ?? nowYm());
  focusCell = true;
  focused.value = start;
  viewYear.value = start.year;
  open.value = true;
}

function closePopup(returnFocus: boolean) {
  open.value = false;
  if (returnFocus) toggleRef.value?.focus();
}

function selectMonth(ym: Temporal.PlainYearMonth) {
  if (!isSelectable(ym)) return;
  selected.value = ym;
  focused.value = ym;
  closePopup(true);
}

useDismiss(rootRef, open, () => (open.value = false), { escape: false });

watch(open, (isOpen, _prev, onCleanup) => {
  if (!isOpen) return;
  const onKey = (e: KeyboardEvent) => {
    if (e.key === 'Escape') {
      e.stopPropagation();
      open.value = false;
      toggleRef.value?.focus();
    }
  };
  document.addEventListener('keydown', onKey);
  onCleanup(() => document.removeEventListener('keydown', onKey));
});

watch([open, focused, viewYear], async () => {
  if (!open.value || !focusCell) return;
  focusCell = false;
  await nextTick();
  const el = gridRef.value?.querySelector<HTMLButtonElement>(
    `[data-month="${focused.value.toString()}"]`,
  );
  el?.focus();
});

const months = computed(() =>
  Array.from({ length: 12 }, (_, i) =>
    Temporal.PlainYearMonth.from({ year: viewYear.value, month: i + 1 }),
  ),
);

const prevDisabled = computed(() => minYm.value != null && viewYear.value <= minYm.value.year);
const nextDisabled = computed(() => maxYm.value != null && viewYear.value >= maxYm.value.year);

const triggerText = computed(() =>
  selected.value
    ? formatMonth(selected.value, props.locale, { year: 'numeric', month: 'long' })
    : props.toggleLabel,
);

function onGridKeyDown(e: KeyboardEvent) {
  const f = focused.value;
  switch (e.key) {
    case 'ArrowLeft':
      moveFocus(f.subtract({ months: 1 }));
      break;
    case 'ArrowRight':
      moveFocus(f.add({ months: 1 }));
      break;
    case 'ArrowUp':
      moveFocus(f.subtract({ months: 3 }));
      break;
    case 'ArrowDown':
      moveFocus(f.add({ months: 3 }));
      break;
    case 'Home':
      moveFocus(f.subtract({ months: (f.month - 1) % 3 }));
      break;
    case 'End':
      moveFocus(f.add({ months: 2 - ((f.month - 1) % 3) }));
      break;
    case 'PageUp':
      moveFocus(f.subtract({ years: 1 }));
      break;
    case 'PageDown':
      moveFocus(f.add({ years: 1 }));
      break;
    case 'Enter':
    case ' ':
      selectMonth(f);
      break;
    default:
      return;
  }
  e.preventDefault();
}

function onTriggerKeyDown(e: KeyboardEvent) {
  if (e.key === 'ArrowDown') {
    e.preventDefault();
    openPopup();
  }
}
</script>

<template>
  <div
    ref="rootRef"
    :class="cx(CLASS, `${CLASS}--${size}`, disabled && `${CLASS}--disabled`)"
  >
    <button
      :id="baseId"
      ref="toggleRef"
      type="button"
      :class="`${CLASS}__trigger`"
      aria-haspopup="dialog"
      :aria-expanded="open"
      :aria-controls="open ? popupId : undefined"
      :aria-label="selected ? `${toggleLabel}: ${triggerText}` : toggleLabel"
      :disabled="disabled"
      @click="open ? closePopup(false) : openPopup()"
      @keydown="onTriggerKeyDown"
    >
      <span :class="cx(`${CLASS}__value`, !selected && `${CLASS}__value--placeholder`)">
        {{ triggerText }}
      </span>
      <span :class="`${CLASS}__icon`">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true">
          <rect x="3" y="4.5" width="18" height="16" rx="2.5" stroke="currentColor" stroke-width="1.7" />
          <path d="M3 9h18M8 2.5v4M16 2.5v4" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" />
        </svg>
      </span>
    </button>

    <div
      v-if="open"
      :id="popupId"
      role="dialog"
      aria-modal="false"
      :aria-labelledby="titleId"
      :class="cx(`${CLASS}__popup`, alignEnd && `${CLASS}__popup--end`)"
    >
      <div :class="`${CLASS}__header`">
        <button
          type="button"
          :class="`${CLASS}__nav`"
          aria-label="Previous year"
          :disabled="prevDisabled"
          @click="viewYear -= 1"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <path d="M15 5l-7 7 7 7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </button>
        <h2 :id="titleId" :class="`${CLASS}__title`" aria-live="polite">{{ viewYear }}</h2>
        <button
          type="button"
          :class="`${CLASS}__nav`"
          aria-label="Next year"
          :disabled="nextDisabled"
          @click="viewYear += 1"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <path d="M9 5l7 7-7 7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </button>
      </div>

      <div ref="gridRef" role="group" :aria-labelledby="titleId" :class="`${CLASS}__grid`">
        <button
          v-for="ym in months"
          :key="ym.toString()"
          type="button"
          :data-month="ym.toString()"
          :class="
            cx(`${CLASS}__month`, {
              [`${CLASS}__month--selected`]: selected != null && ym.equals(selected),
            })
          "
          :tabindex="ym.equals(focused) ? 0 : -1"
          :aria-pressed="selected != null && ym.equals(selected)"
          :aria-disabled="!isSelectable(ym) || undefined"
          :aria-label="formatMonth(ym, locale, { year: 'numeric', month: 'long' })"
          @click="selectMonth(ym)"
          @keydown="onGridKeyDown"
          @focus="focused = ym"
        >
          {{ formatMonth(ym, locale, { month: 'short' }) }}
        </button>
      </div>
    </div>
  </div>
</template>

// packages/react/src/components/MonthPicker/MonthPicker.tsx
import {
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type KeyboardEvent as ReactKeyboardEvent,
} from 'react';
import { cx } from '../../utils/cx';
import { getDateTimeFormat, toPlainYearMonth, toUtcDate, type PlainYearMonthInput } from '../../utils/datetime';
import { useControllableState, useDismiss } from '../../hooks';
import type { SizeToken } from '../../tokens';

const CLASS = 'lily-month-picker';

export interface MonthPickerProps {
  /** Selected month (controlled). Pass `null` for "no selection". */
  value?: Temporal.PlainYearMonth | null;
  /** Initial month (uncontrolled). @default null */
  defaultValue?: Temporal.PlainYearMonth | null;
  /** Called with the new month (or `null` when cleared). */
  onChange?: (value: Temporal.PlainYearMonth | null) => void;
  /** Earliest selectable month (inclusive). ISO `YYYY-MM` strings accepted. */
  min?: PlainYearMonthInput;
  /** Latest selectable month (inclusive). ISO `YYYY-MM` strings accepted. */
  max?: PlainYearMonthInput;
  /** BCP-47 locale for month names. Defaults to the host locale. */
  locale?: Intl.LocalesArgument;
  /** Disable the whole control. */
  disabled?: boolean;
  /** Control size. @default 'md' */
  size?: Extract<SizeToken, 'sm' | 'md' | 'lg'>;
  /** Align the popup to the trigger's end (right) edge. @default false */
  alignEnd?: boolean;
  /** Accessible label for the trigger when no month is chosen. @default 'Choose month' */
  toggleLabel?: string;
  /** `id` for the trigger button (an auto-generated id is used otherwise). */
  id?: string;
  className?: string;
}

/** Coerce an optional `PlainYearMonthInput` to a `PlainYearMonth` (or `undefined`). */
function toBound(input: PlainYearMonthInput | undefined): Temporal.PlainYearMonth | undefined {
  return input == null ? undefined : toPlainYearMonth(input);
}

/** Localized month label via a fixed-UTC `Date`; the logic stays in Temporal. */
function formatMonth(
  ym: Temporal.PlainYearMonth,
  locale: Intl.LocalesArgument,
  options: Intl.DateTimeFormatOptions,
): string {
  const utc = toUtcDate(ym.year, ym.month, 1);
  // Cached per locale + options: the grid formats 12+ labels on every render.
  return getDateTimeFormat(locale, { timeZone: 'UTC', ...options }).format(utc);
}

/**
 * MonthPicker — pick a calendar month from a 12-month grid with prev/next year
 * navigation. The value is a **`Temporal.PlainYearMonth`** (this library models
 * all date/time with the Temporal API).
 *
 * Grid keyboard model (focus inside the panel):
 * - Arrow keys move by one / three months, `Home`/`End` to row edges
 * - `PageUp`/`PageDown` move by year
 * - `Enter`/`Space` selects, `Escape` closes
 *
 * @example
 * ```tsx
 * <MonthPicker
 *   defaultValue={Temporal.PlainYearMonth.from('2026-05')}
 *   onChange={setMonth}
 * />
 * ```
 */
export function MonthPicker({
  value,
  defaultValue = null,
  onChange,
  min,
  max,
  locale,
  disabled = false,
  size = 'md',
  alignEnd = false,
  toggleLabel = 'Choose month',
  id,
  className,
}: MonthPickerProps) {
  const reactId = useId();
  const baseId = id ?? reactId;
  const popupId = `${baseId}-popup`;
  const titleId = `${baseId}-title`;

  const rootRef = useRef<HTMLDivElement>(null);
  const toggleRef = useRef<HTMLButtonElement>(null);
  const gridRef = useRef<HTMLDivElement>(null);
  const focusCellRef = useRef(false);

  const minYm = useMemo(() => toBound(min), [min]);
  const maxYm = useMemo(() => toBound(max), [max]);

  const [selected, setSelected] = useControllableState<Temporal.PlainYearMonth | null>({
    value,
    defaultValue,
    onChange,
  });

  const [open, setOpen] = useState(false);
  const [viewYear, setViewYear] = useState<number>(() =>
    (selected ?? Temporal.Now.plainDateISO().toPlainYearMonth()).year,
  );
  const [focused, setFocused] = useState<Temporal.PlainYearMonth>(
    () => selected ?? clamp(Temporal.Now.plainDateISO().toPlainYearMonth(), minYm, maxYm),
  );

  function isSelectable(ym: Temporal.PlainYearMonth): boolean {
    if (minYm && Temporal.PlainYearMonth.compare(ym, minYm) < 0) return false;
    if (maxYm && Temporal.PlainYearMonth.compare(ym, maxYm) > 0) return false;
    return true;
  }

  function clampToBounds(ym: Temporal.PlainYearMonth): Temporal.PlainYearMonth {
    return clamp(ym, minYm, maxYm);
  }

  function moveFocus(ym: Temporal.PlainYearMonth) {
    const next = clampToBounds(ym);
    focusCellRef.current = true;
    setFocused(next);
    setViewYear(next.year);
  }

  function openPopup() {
    if (disabled) return;
    const start = clampToBounds(selected ?? Temporal.Now.plainDateISO().toPlainYearMonth());
    focusCellRef.current = true;
    setFocused(start);
    setViewYear(start.year);
    setOpen(true);
  }

  function closePopup(returnFocus: boolean) {
    setOpen(false);
    if (returnFocus) toggleRef.current?.focus();
  }

  function selectMonth(ym: Temporal.PlainYearMonth) {
    if (!isSelectable(ym)) return;
    setSelected(ym);
    setFocused(ym);
    closePopup(true);
  }

  useDismiss(rootRef, open, () => setOpen(false), { escape: false });

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.stopPropagation();
        setOpen(false);
        toggleRef.current?.focus();
      }
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open]);

  useEffect(() => {
    if (!open || !focusCellRef.current) return;
    focusCellRef.current = false;
    const el = gridRef.current?.querySelector<HTMLButtonElement>(
      `[data-month="${focused.toString()}"]`,
    );
    el?.focus();
  }, [open, focused, viewYear]);

  const months = useMemo(
    () => Array.from({ length: 12 }, (_, i) => Temporal.PlainYearMonth.from({ year: viewYear, month: i + 1 })),
    [viewYear],
  );

  const prevDisabled =
    minYm != null && viewYear <= minYm.year;
  const nextDisabled =
    maxYm != null && viewYear >= maxYm.year;

  function onGridKeyDown(e: ReactKeyboardEvent<HTMLButtonElement>) {
    switch (e.key) {
      case 'ArrowLeft':
        moveFocus(focused.subtract({ months: 1 }));
        break;
      case 'ArrowRight':
        moveFocus(focused.add({ months: 1 }));
        break;
      case 'ArrowUp':
        moveFocus(focused.subtract({ months: 3 }));
        break;
      case 'ArrowDown':
        moveFocus(focused.add({ months: 3 }));
        break;
      case 'Home':
        moveFocus(focused.subtract({ months: (focused.month - 1) % 3 }));
        break;
      case 'End':
        moveFocus(focused.add({ months: 2 - ((focused.month - 1) % 3) }));
        break;
      case 'PageUp':
        moveFocus(focused.subtract({ years: 1 }));
        break;
      case 'PageDown':
        moveFocus(focused.add({ years: 1 }));
        break;
      case 'Enter':
      case ' ':
        selectMonth(focused);
        break;
      default:
        return;
    }
    e.preventDefault();
  }

  const triggerText = selected
    ? formatMonth(selected, locale, { year: 'numeric', month: 'long' })
    : toggleLabel;

  return (
    <div
      ref={rootRef}
      className={cx(
        CLASS,
        `${CLASS}--${size}`,
        disabled && `${CLASS}--disabled`,
        className,
      )}
    >
      <button
        ref={toggleRef}
        type="button"
        id={baseId}
        className={`${CLASS}__trigger`}
        aria-haspopup="dialog"
        aria-expanded={open}
        aria-controls={open ? popupId : undefined}
        aria-label={selected ? `${toggleLabel}: ${triggerText}` : toggleLabel}
        disabled={disabled}
        onClick={() => (open ? closePopup(false) : openPopup())}
        onKeyDown={(e) => {
          if (e.key === 'ArrowDown') {
            e.preventDefault();
            openPopup();
          }
        }}
      >
        <span className={cx(`${CLASS}__value`, !selected && `${CLASS}__value--placeholder`)}>
          {triggerText}
        </span>
        <span className={`${CLASS}__icon`}>
          <CalendarIcon />
        </span>
      </button>

      {open && (
        <div
          id={popupId}
          role="dialog"
          aria-modal="false"
          aria-labelledby={titleId}
          className={cx(`${CLASS}__popup`, alignEnd && `${CLASS}__popup--end`)}
        >
          <div className={`${CLASS}__header`}>
            <button
              type="button"
              className={`${CLASS}__nav`}
              aria-label="Previous year"
              disabled={prevDisabled}
              onClick={() => setViewYear((y) => y - 1)}
            >
              <ChevronIcon dir="left" />
            </button>
            <h2 id={titleId} className={`${CLASS}__title`} aria-live="polite">
              {viewYear}
            </h2>
            <button
              type="button"
              className={`${CLASS}__nav`}
              aria-label="Next year"
              disabled={nextDisabled}
              onClick={() => setViewYear((y) => y + 1)}
            >
              <ChevronIcon dir="right" />
            </button>
          </div>

          <div
            ref={gridRef}
            role="group"
            aria-labelledby={titleId}
            className={`${CLASS}__grid`}
          >
            {months.map((ym) => {
              const isSelected = selected != null && ym.equals(selected);
              const isFocused = ym.equals(focused);
              const selectable = isSelectable(ym);
              return (
                <button
                  key={ym.toString()}
                  type="button"
                  data-month={ym.toString()}
                  className={cx(`${CLASS}__month`, {
                    [`${CLASS}__month--selected`]: isSelected,
                  })}
                  tabIndex={isFocused ? 0 : -1}
                  aria-pressed={isSelected}
                  aria-disabled={!selectable || undefined}
                  aria-label={formatMonth(ym, locale, { year: 'numeric', month: 'long' })}
                  onClick={() => selectMonth(ym)}
                  onKeyDown={onGridKeyDown}
                  onFocus={() => setFocused(ym)}
                >
                  {formatMonth(ym, locale, { month: 'short' })}
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

// --- Pure helpers (Temporal) -----------------------------------------------

/** Clamp `ym` into the inclusive `[min, max]` range. */
function clamp(
  ym: Temporal.PlainYearMonth,
  min: Temporal.PlainYearMonth | undefined,
  max: Temporal.PlainYearMonth | undefined,
): Temporal.PlainYearMonth {
  if (min && Temporal.PlainYearMonth.compare(ym, min) < 0) return min;
  if (max && Temporal.PlainYearMonth.compare(ym, max) > 0) return max;
  return ym;
}

// --- Inline icons (no external assets; inherit currentColor) ----------------

function CalendarIcon() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <rect x="3" y="4.5" width="18" height="16" rx="2.5" stroke="currentColor" strokeWidth="1.7" />
      <path d="M3 9h18M8 2.5v4M16 2.5v4" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" />
    </svg>
  );
}

function ChevronIcon({ dir }: { dir: 'left' | 'right' }) {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d={dir === 'left' ? 'M15 5l-7 7 7 7' : 'M9 5l7 7-7 7'}
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
