// packages/react/src/components/Select/Select.tsx
import { forwardRef, type SelectHTMLAttributes } from 'react';
import { cx } from '../../utils/cx';
import { useFieldControl } from '../FormField';

export type SelectProps = SelectHTMLAttributes<HTMLSelectElement>;

const CLASS = 'lily-select';

/**
 * Select — a native `<select>` dropdown (accessible by default). Use this for a
 * fixed list of options; for a searchable / typeahead list with filtering, use
 * `Combobox` instead.
 *
 * Inside a {@link FormField} it inherits field wiring automatically.
 *
 * @example
 * ```tsx
 * <FormField label="Country">
 *   <Select>
 *     <option value="jp">Japan</option>
 *     <option value="us">USA</option>
 *   </Select>
 * </FormField>
 * ```
 */
export const Select = forwardRef<HTMLSelectElement, SelectProps>(function Select(
  { className, children, ...rest },
  ref,
) {
  const fieldProps = useFieldControl(rest);
  return (
    <select ref={ref} className={cx(CLASS, className)} {...fieldProps}>
      {children}
    </select>
  );
});

// packages/vue/src/components/Select/Select.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cx } from '../../utils/cx';
import { useFieldControl } from '../../composables/field';

/**
 * Select — a native dropdown control (accessible by default). Supports `v-model`.
 *
 * Inside a {@link FormField} it inherits `id`, `aria-describedby`,
 * `aria-invalid`, and `required` automatically.
 *
 * @example
 * ```vue
 * <FormField label="Country">
 *   <Select v-model="country">
 *     <option value="jp">Japan</option>
 *     <option value="us">USA</option>
 *   </Select>
 * </FormField>
 * ```
 */
defineProps<{
  /** Bound value (`v-model`). */
  modelValue?: string | number;
}>();

const emit = defineEmits<{ 'update:modelValue': [value: string] }>();

const fieldAttrs = useFieldControl(() => ({}));

const classes = computed(() => cx('lily-select'));
</script>

<template>
  <select
    :class="classes"
    v-bind="fieldAttrs"
    :value="modelValue"
    @change="emit('update:modelValue', ($event.target as HTMLSelectElement).value)"
  >
    <slot />
  </select>
</template>
