// packages/vue/src/components/ButtonGroup/ButtonGroup.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cx } from '../../utils/cx';

/**
 * ButtonGroup — segments multiple {@link Button}s into a single control.
 *
 * Renders `role="group"`; provide a `label` so the group's purpose is announced.
 *
 * @example
 * ```vue
 * <ButtonGroup label="Text alignment">
 *   <Button>Left</Button>
 *   <Button>Center</Button>
 *   <Button>Right</Button>
 * </ButtonGroup>
 * ```
 */
const props = withDefaults(
  defineProps<{
    /** Layout orientation. */
    orientation?: 'horizontal' | 'vertical';
    /** Accessible label describing the group. */
    label?: string;
  }>(),
  { orientation: 'horizontal' },
);

const classes = computed(() =>
  cx('lily-btn-group', props.orientation === 'vertical' && 'lily-btn-group--vertical'),
);
</script>

<template>
  <div role="group" :aria-label="label" :class="classes">
    <slot />
  </div>
</template>

// packages/react/src/components/ButtonGroup/ButtonGroup.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import { cx } from '../../utils/cx';

export interface ButtonGroupProps extends HTMLAttributes<HTMLDivElement> {
  /** Layout orientation. @default 'horizontal' */
  orientation?: 'horizontal' | 'vertical';
  /** Accessible label describing the group. */
  label?: string;
}

const CLASS = 'lily-btn-group';

/**
 * ButtonGroup — segments multiple {@link Button}s into a single control.
 *
 * Renders `role="group"`; provide a `label` so the group's purpose is announced.
 *
 * @example
 * ```tsx
 * <ButtonGroup label="Text alignment">
 *   <Button>Left</Button>
 *   <Button>Center</Button>
 *   <Button>Right</Button>
 * </ButtonGroup>
 * ```
 */
export const ButtonGroup = forwardRef<HTMLDivElement, ButtonGroupProps>(function ButtonGroup(
  { orientation = 'horizontal', label, className, children, ...rest },
  ref,
) {
  return (
    <div
      ref={ref}
      role="group"
      aria-label={label}
      className={cx(CLASS, orientation === 'vertical' && `${CLASS}--vertical`, className)}
      {...rest}
    >
      {children}
    </div>
  );
});
