// packages/react/src/components/BackTop/BackTop.tsx
import { forwardRef, useEffect, useState, type ButtonHTMLAttributes, type ReactNode } from 'react';
import { cx } from '../../utils/cx';
import { prefersReducedMotion } from '../../motion/level';

export interface BackTopProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Scroll distance (px) before the button appears. @default 400 */
  visibilityHeight?: number;
  /** Accessible label. @default 'Back to top' */
  label?: string;
  /** Custom icon (defaults to an up arrow). */
  children?: ReactNode;
}

/**
 * BackTop — a floating button that appears after scrolling past
 * `visibilityHeight` and smoothly returns to the top. Respects reduced motion.
 *
 * @example
 * ```tsx
 * <BackTop label="トップへ戻る" />
 * ```
 */
export const BackTop = forwardRef<HTMLButtonElement, BackTopProps>(function BackTop(
  { visibilityHeight = 400, label = 'Back to top', className, children, onClick, ...rest },
  ref,
) {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const onScroll = () => setVisible(window.scrollY > visibilityHeight);
    onScroll();
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, [visibilityHeight]);

  return (
    <button
      ref={ref}
      type="button"
      className={cx('lily-back-top', className)}
      aria-label={label}
      hidden={!visible}
      onClick={(e) => {
        window.scrollTo({ top: 0, behavior: prefersReducedMotion() ? 'auto' : 'smooth' });
        onClick?.(e);
      }}
      {...rest}
    >
      {children ?? (
        <span aria-hidden="true">↑</span>
      )}
    </button>
  );
});

// packages/vue/src/components/BackTop/BackTop.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import { cx } from '../../utils/cx';
import { prefersReducedMotion } from '../../composables/motion';

/**
 * BackTop — a floating button that appears after scrolling past
 * `visibilityHeight` and smoothly returns to the top. Respects reduced motion.
 *
 * @example
 * ```vue
 * <BackTop label="トップへ戻る" />
 * ```
 */
const props = withDefaults(defineProps<{ visibilityHeight?: number; label?: string }>(), {
  visibilityHeight: 400,
  label: 'Back to top',
});

const visible = ref(false);
function onScroll(): void {
  visible.value = window.scrollY > props.visibilityHeight;
}
onMounted(() => {
  onScroll();
  window.addEventListener('scroll', onScroll, { passive: true });
});
onUnmounted(() => window.removeEventListener('scroll', onScroll));

function toTop(): void {
  window.scrollTo({ top: 0, behavior: prefersReducedMotion() ? 'auto' : 'smooth' });
}
</script>

<template>
  <button type="button" :class="cx('lily-back-top')" :aria-label="label" :hidden="!visible" @click="toTop">
    <slot><span aria-hidden="true">↑</span></slot>
  </button>
</template>
