// packages/react/src/components/Transfer/Transfer.tsx
import { forwardRef, useState } from 'react';
import { cx } from '../../utils/cx';
import { useControllableState } from '../../hooks';
import { Button } from '../Button';

export interface TransferItem {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface TransferProps {
  /** All available items. */
  items: TransferItem[];
  /** Controlled values currently in the target list. */
  value?: string[];
  /** Initial target values when uncontrolled. @default [] */
  defaultValue?: string[];
  /** Called with the updated target values. */
  onChange?: (target: string[]) => void;
  /** `[source, target]` list titles. @default ['Available', 'Selected'] */
  titles?: [string, string];
  /** Label for the move-to-target button. @default 'Add selected' */
  toTargetLabel?: string;
  /** Label for the move-to-source button. @default 'Remove selected' */
  toSourceLabel?: string;
  className?: string;
}

/**
 * Transfer — move items between a source and a target list. Each row is a
 * labeled checkbox; the controls move the checked rows across.
 *
 * @example
 * ```tsx
 * <Transfer items={all} defaultValue={['a']} titles={['候補', '選択済み']} />
 * ```
 */
export const Transfer = forwardRef<HTMLDivElement, TransferProps>(function Transfer(
  { items, value: valueProp, defaultValue = [], onChange, titles = ['Available', 'Selected'], toTargetLabel = 'Add selected', toSourceLabel = 'Remove selected', className },
  ref,
) {
  const [target, setTarget] = useControllableState<string[]>({ value: valueProp, defaultValue, onChange });
  const [checked, setChecked] = useState<Set<string>>(new Set());
  const targetSet = new Set(target);

  const sourceItems = items.filter((it) => !targetSet.has(it.value));
  const targetItems = items.filter((it) => targetSet.has(it.value));

  const toggle = (v: string) => {
    const next = new Set(checked);
    if (next.has(v)) next.delete(v);
    else next.add(v);
    setChecked(next);
  };

  const moveToTarget = () => {
    const moving = sourceItems.filter((it) => checked.has(it.value) && !it.disabled).map((it) => it.value);
    setTarget([...target, ...moving]);
    setChecked(new Set([...checked].filter((v) => !moving.includes(v))));
  };
  const moveToSource = () => {
    const moving = targetItems.filter((it) => checked.has(it.value) && !it.disabled).map((it) => it.value);
    setTarget(target.filter((v) => !moving.includes(v)));
    setChecked(new Set([...checked].filter((v) => !moving.includes(v))));
  };

  const renderList = (title: string, list: TransferItem[]) => (
    <div className="lily-transfer__list">
      <div className="lily-transfer__header">{title}</div>
      <ul className="lily-transfer__items">
        {list.map((it) => (
          <li key={it.value}>
            <label className="lily-transfer__item">
              <input
                type="checkbox"
                checked={checked.has(it.value)}
                disabled={it.disabled}
                onChange={() => toggle(it.value)}
              />
              <span>{it.label}</span>
            </label>
          </li>
        ))}
      </ul>
    </div>
  );

  const hasSourceChecked = sourceItems.some((it) => checked.has(it.value));
  const hasTargetChecked = targetItems.some((it) => checked.has(it.value));

  return (
    <div ref={ref} className={cx('lily-transfer', className)}>
      {renderList(titles[0], sourceItems)}
      <div className="lily-transfer__actions">
        <Button size="sm" variant="outline" aria-label={toTargetLabel} disabled={!hasSourceChecked} onClick={moveToTarget}>
          <span aria-hidden="true">›</span>
        </Button>
        <Button size="sm" variant="outline" aria-label={toSourceLabel} disabled={!hasTargetChecked} onClick={moveToSource}>
          <span aria-hidden="true">‹</span>
        </Button>
      </div>
      {renderList(titles[1], targetItems)}
    </div>
  );
});

// packages/vue/src/components/Transfer/Transfer.vue
<script lang="ts">
export interface TransferItem {
  value: string;
  label: string;
  disabled?: boolean;
}
</script>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { cx } from '../../utils/cx';
import Button from '../Button/Button.vue';

/**
 * Transfer — move items between a source and a target list. Bind the target
 * values with `v-model`.
 *
 * @example
 * ```vue
 * <Transfer v-model="selected" :items="all" :titles="['候補', '選択済み']" />
 * ```
 */
const props = withDefaults(
  defineProps<{
    items: TransferItem[];
    titles?: [string, string];
    toTargetLabel?: string;
    toSourceLabel?: string;
  }>(),
  { titles: () => ['Available', 'Selected'], toTargetLabel: 'Add selected', toSourceLabel: 'Remove selected' },
);

const model = defineModel<string[]>({ default: () => [] });
const checked = ref<Set<string>>(new Set());
const targetSet = computed(() => new Set(model.value));
const sourceItems = computed(() => props.items.filter((it) => !targetSet.value.has(it.value)));
const targetItems = computed(() => props.items.filter((it) => targetSet.value.has(it.value)));
const hasSourceChecked = computed(() => sourceItems.value.some((it) => checked.value.has(it.value)));
const hasTargetChecked = computed(() => targetItems.value.some((it) => checked.value.has(it.value)));

function toggle(v: string): void {
  const next = new Set(checked.value);
  if (next.has(v)) next.delete(v);
  else next.add(v);
  checked.value = next;
}
function moveToTarget(): void {
  const moving = sourceItems.value.filter((it) => checked.value.has(it.value) && !it.disabled).map((it) => it.value);
  model.value = [...model.value, ...moving];
  checked.value = new Set([...checked.value].filter((v) => !moving.includes(v)));
}
function moveToSource(): void {
  const moving = targetItems.value.filter((it) => checked.value.has(it.value) && !it.disabled).map((it) => it.value);
  model.value = model.value.filter((v) => !moving.includes(v));
  checked.value = new Set([...checked.value].filter((v) => !moving.includes(v)));
}
</script>

<template>
  <div :class="cx('lily-transfer')">
    <div class="lily-transfer__list">
      <div class="lily-transfer__header">{{ titles[0] }}</div>
      <ul class="lily-transfer__items">
        <li v-for="it in sourceItems" :key="it.value">
          <label class="lily-transfer__item">
            <input type="checkbox" :checked="checked.has(it.value)" :disabled="it.disabled" @change="toggle(it.value)" />
            <span>{{ it.label }}</span>
          </label>
        </li>
      </ul>
    </div>
    <div class="lily-transfer__actions">
      <Button size="sm" variant="outline" :aria-label="toTargetLabel" :disabled="!hasSourceChecked" @click="moveToTarget">
        <span aria-hidden="true">›</span>
      </Button>
      <Button size="sm" variant="outline" :aria-label="toSourceLabel" :disabled="!hasTargetChecked" @click="moveToSource">
        <span aria-hidden="true">‹</span>
      </Button>
    </div>
    <div class="lily-transfer__list">
      <div class="lily-transfer__header">{{ titles[1] }}</div>
      <ul class="lily-transfer__items">
        <li v-for="it in targetItems" :key="it.value">
          <label class="lily-transfer__item">
            <input type="checkbox" :checked="checked.has(it.value)" :disabled="it.disabled" @change="toggle(it.value)" />
            <span>{{ it.label }}</span>
          </label>
        </li>
      </ul>
    </div>
  </div>
</template>
