// packages/react/src/components/Popover/Popover.tsx
import {
  cloneElement,
  useId,
  useRef,
  type ReactElement,
  type ReactNode,
} from 'react';
import { cx } from '../../utils/cx';
import { useControllableState, useDismiss } from '../../hooks';

export interface PopoverProps {
  /** Optional header shown above the body. */
  title?: ReactNode;
  /** Popover body content. */
  content: ReactNode;
  /**
   * The trigger element. It receives `aria-expanded`, `aria-haspopup`, and an
   * onClick toggle; it must be a focusable element.
   */
  children: ReactElement<{
    'aria-expanded'?: boolean;
    'aria-haspopup'?: 'dialog';
    onClick?: (e: React.MouseEvent) => void;
  }>;
  /** Controlled open state. */
  open?: boolean;
  /** Initial open state (uncontrolled). @default false */
  defaultOpen?: boolean;
  /** Called when open state changes. */
  onOpenChange?: (open: boolean) => void;
  className?: string;
}

const CLASS = 'lily-popover';

/**
 * Popover — a click-triggered overlay with optional title and rich content.
 *
 * Uses `role="dialog"` (non-modal) and closes on Escape/outside click.
 *
 * @example
 * ```tsx
 * <Popover title="Info" content={<p>Details…</p>}>
 *   <button>More</button>
 * </Popover>
 * ```
 */
export function Popover({
  title,
  content,
  children,
  open,
  defaultOpen = false,
  onOpenChange,
  className,
}: PopoverProps) {
  const id = useId();
  const rootRef = useRef<HTMLSpanElement>(null);
  const [isOpen, setOpen] = useControllableState<boolean>({
    value: open,
    defaultValue: defaultOpen,
    onChange: onOpenChange,
  });

  useDismiss(rootRef, isOpen, () => setOpen(false));

  const trigger = cloneElement(children, {
    'aria-expanded': isOpen,
    'aria-haspopup': 'dialog',
    onClick: (e: React.MouseEvent) => {
      setOpen(!isOpen);
      children.props.onClick?.(e);
    },
  });

  return (
    <span ref={rootRef} style={{ position: 'relative', display: 'inline-flex' }}>
      {trigger}
      <div
        role="dialog"
        id={id}
        aria-label={typeof title === 'string' ? title : undefined}
        className={cx(CLASS, 'lily-animate', 'lily-animate--zoom-in', 'lily-animate--snappy', className)}
        hidden={!isOpen}
      >
        {title && <div className={`${CLASS}__header`}>{title}</div>}
        <div className={`${CLASS}__body`}>{content}</div>
      </div>
    </span>
  );
}

// packages/vue/src/components/Popover/Popover.vue
<script lang="ts">
// no type exports needed for Popover
</script>

<script setup lang="ts">
import { ref, useId } from 'vue';
import { cx } from '../../utils/cx';
import { useDismiss } from '../../composables/interactions';

/**
 * Popover — a click-triggered overlay with optional title and rich content.
 *
 * Uses `role="dialog"` (non-modal) and closes on Escape/outside click. The
 * trigger is the default slot; it receives `aria-expanded` + `aria-haspopup`
 * and a click toggle via a wrapping element. Bind open state with
 * `v-model:open`.
 *
 * @example
 * ```vue
 * <Popover title="Info" content="Details…">
 *   <button>More</button>
 * </Popover>
 * ```
 */
const props = defineProps<{
  /** Optional header shown above the body (or use the `#title` slot). */
  title?: string;
  /** Popover body content (or use the `#content` slot). */
  content?: string;
}>();

/** Open state; bind with `v-model:open`. */
const open = defineModel<boolean>('open', { default: false });

const id = useId();
const rootRef = ref<HTMLSpanElement | null>(null);
const CLASS = 'lily-popover';

useDismiss(rootRef, open, () => (open.value = false));
</script>

<template>
  <span
    ref="rootRef"
    style="position: relative; display: inline-flex"
    :aria-expanded="open"
    aria-haspopup="dialog"
    @click="open = !open"
  >
    <slot />
    <div
      :id="id"
      role="dialog"
      :aria-label="props.title || undefined"
      :class="cx(CLASS, 'lily-animate', 'lily-animate--zoom-in', 'lily-animate--snappy')"
      :hidden="!open"
    >
      <div v-if="$slots.title || title" :class="`${CLASS}__header`">
        <slot name="title">{{ title }}</slot>
      </div>
      <div :class="`${CLASS}__body`">
        <slot name="content">{{ content }}</slot>
      </div>
    </div>
  </span>
</template>
