// packages/vue/src/components/Footer/Footer.vue
<script setup lang="ts">
import { cx } from '../../utils/cx';

/**
 * Footer — the page's `contentinfo` landmark, the counterpart to Navbar. A
 * `<footer>` region with a centered inner row composed via the default slot.
 *
 * @example
 * ```vue
 * <Footer>
 *   <p>© 2026 Lily</p>
 *   <a href="/terms">Terms</a>
 * </Footer>
 * ```
 */
withDefaults(
  defineProps<{
    /** Draw a top border separating the footer from the page. */
    bordered?: boolean;
  }>(),
  { bordered: true },
);
</script>

<template>
  <footer :class="cx('lily-footer', bordered && 'lily-footer--bordered')">
    <div class="lily-footer__inner"><slot /></div>
  </footer>
</template>

// packages/react/src/components/Footer/Footer.tsx
import { forwardRef, type HTMLAttributes, type ReactNode } from 'react';
import { cx } from '../../utils/cx';

export interface FooterProps extends HTMLAttributes<HTMLElement> {
  /** Footer content (links, legal text, columns — composed freely). */
  children: ReactNode;
  /** Draw a top border separating the footer from the page. @default true */
  bordered?: boolean;
}

const CLASS = 'lily-footer';

/**
 * Footer — the page's `contentinfo` landmark. The counterpart to {@link Navbar}:
 * a `<footer>` region with a centered inner row you compose freely (links,
 * legal text, columns).
 *
 * @example
 * ```tsx
 * <Footer>
 *   <p>© 2026 Lily</p>
 *   <a href="/terms">Terms</a>
 * </Footer>
 * ```
 */
export const Footer = forwardRef<HTMLElement, FooterProps>(function Footer(
  { children, bordered = true, className, ...rest },
  ref,
) {
  return (
    <footer
      ref={ref}
      className={cx(CLASS, bordered && `${CLASS}--bordered`, className)}
      {...rest}
    >
      <div className={`${CLASS}__inner`}>{children}</div>
    </footer>
  );
});
