// packages/react/src/components/CloseButton/CloseButton.tsx
import { forwardRef, type ButtonHTMLAttributes } from 'react';
import { cx } from '../../utils/cx';

export interface CloseButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Accessible label for the dismiss action. @default 'Close' */
  label?: string;
}

const CLASS = 'lily-close';

/**
 * CloseButton — a standard dismiss control (×).
 *
 * Renders a native `<button>` with an accessible label and a decorative glyph.
 *
 * @example
 * ```tsx
 * <CloseButton onClick={dismiss} label="Dismiss notification" />
 * ```
 */
export const CloseButton = forwardRef<HTMLButtonElement, CloseButtonProps>(function CloseButton(
  { label = 'Close', className, type, ...rest },
  ref,
) {
  return (
    <button
      ref={ref}
      type={type ?? 'button'}
      className={cx(CLASS, className)}
      aria-label={label}
      {...rest}
    >
      <span aria-hidden="true">&times;</span>
    </button>
  );
});

// packages/vue/src/components/CloseButton/CloseButton.vue
<script setup lang="ts">
import { cx } from '../../utils/cx';

/**
 * CloseButton — a standard dismiss control (×).
 *
 * Renders a native `<button>` with an accessible label and a decorative glyph.
 * A user-supplied `class` is merged automatically by Vue.
 *
 * @example
 * ```vue
 * <CloseButton @click="dismiss" label="Dismiss notification" />
 * ```
 */
withDefaults(
  defineProps<{
    /** Accessible label for the dismiss action. */
    label?: string;
    /** Native button type. */
    type?: 'button' | 'submit' | 'reset';
  }>(),
  { label: 'Close', type: 'button' },
);
</script>

<template>
  <button :type="type" :class="cx('lily-close')" :aria-label="label">
    <span aria-hidden="true">&times;</span>
  </button>
</template>
