// packages/vue/src/components/DateRangePicker/DateRangePicker.vue
<script lang="ts">
import type { Weekday } from '../DatePicker/DatePicker.vue';

/** A `[start, end]` date range (either side may be `null`). */
export type DateRange = [Temporal.PlainDate | null, Temporal.PlainDate | null];
export type { Weekday };
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { cx } from '../../utils/cx';
import DatePicker from '../DatePicker/DatePicker.vue';
import type { PlainDateInput } from '../../utils/datetime';

/**
 * DateRangePicker — pick a start and end date with two coordinated DatePickers.
 * The start field caps the end's minimum and vice-versa. Bind with `v-model`.
 *
 * @example
 * ```vue
 * <DateRangePicker v-model="range" start-label="開始日" end-label="終了日" />
 * ```
 */
withDefaults(
  defineProps<{
    min?: PlainDateInput;
    max?: PlainDateInput;
    locale?: Intl.LocalesArgument;
    weekStartsOn?: Weekday;
    disabled?: boolean;
    startLabel?: string;
    endLabel?: string;
    separator?: string;
  }>(),
  { weekStartsOn: 1, disabled: false, startLabel: 'Start date', endLabel: 'End date', separator: '–' },
);

const model = defineModel<DateRange>({ default: () => [null, null] });
const start = computed(() => model.value[0]);
const end = computed(() => model.value[1]);

function setStart(d: Temporal.PlainDate | null): void {
  model.value = [d, end.value];
}
function setEnd(d: Temporal.PlainDate | null): void {
  model.value = [start.value, d];
}
</script>

<template>
  <div :class="cx('lily-date-range-picker')">
    <DatePicker
      :model-value="start"
      :max="end ?? max"
      :min="min"
      :locale="locale"
      :week-starts-on="weekStartsOn"
      :disabled="disabled"
      :input-props="{ 'aria-label': startLabel }"
      @update:model-value="setStart"
    />
    <span class="lily-date-range-picker__sep" aria-hidden="true">{{ separator }}</span>
    <DatePicker
      :model-value="end"
      :min="start ?? min"
      :max="max"
      :locale="locale"
      :week-starts-on="weekStartsOn"
      :disabled="disabled"
      :input-props="{ 'aria-label': endLabel }"
      @update:model-value="setEnd"
    />
  </div>
</template>

// packages/react/src/components/DateRangePicker/DateRangePicker.tsx
import { forwardRef, type ReactNode } from 'react';
import { cx } from '../../utils/cx';
import { useControllableState } from '../../hooks';
import { DatePicker, type Weekday } from '../DatePicker';
import type { PlainDateInput } from '../../utils/datetime';

/** A `[start, end]` date range (either side may be `null`). */
export type DateRange = [Temporal.PlainDate | null, Temporal.PlainDate | null];

export interface DateRangePickerProps {
  /** Controlled `[start, end]` range. */
  value?: DateRange;
  /** Initial range when uncontrolled. @default [null, null] */
  defaultValue?: DateRange;
  /** Called with the updated range. */
  onChange?: (range: DateRange) => void;
  /** Earliest selectable date. */
  min?: PlainDateInput;
  /** Latest selectable date. */
  max?: PlainDateInput;
  /** BCP-47 locale for month/weekday names. */
  locale?: Intl.LocalesArgument;
  /** Which weekday the grid starts on. @default 1 (Monday) */
  weekStartsOn?: Weekday;
  /** Disable both fields. @default false */
  disabled?: boolean;
  /** Accessible label for the start field. @default 'Start date' */
  startLabel?: string;
  /** Accessible label for the end field. @default 'End date' */
  endLabel?: string;
  /** Separator between the two fields. @default '–' */
  separator?: ReactNode;
  className?: string;
}

/**
 * DateRangePicker — pick a start and end date with two coordinated
 * {@link DatePicker}s. The start field caps the end's minimum and vice-versa,
 * so the range can never invert.
 *
 * @example
 * ```tsx
 * <DateRangePicker onChange={([from, to]) => …} />
 * ```
 */
export const DateRangePicker = forwardRef<HTMLDivElement, DateRangePickerProps>(function DateRangePicker(
  { value: valueProp, defaultValue = [null, null], onChange, min, max, locale, weekStartsOn = 1, disabled = false, startLabel = 'Start date', endLabel = 'End date', separator = '–', className },
  ref,
) {
  const [range, setRange] = useControllableState<DateRange>({ value: valueProp, defaultValue, onChange });
  const [start, end] = range;

  return (
    <div ref={ref} className={cx('lily-date-range-picker', className)}>
      <DatePicker
        value={start}
        max={end ?? max}
        min={min}
        locale={locale}
        weekStartsOn={weekStartsOn}
        disabled={disabled}
        inputProps={{ 'aria-label': startLabel }}
        onChange={(d) => setRange([d, end])}
      />
      <span className="lily-date-range-picker__sep" aria-hidden="true">
        {separator}
      </span>
      <DatePicker
        value={end}
        min={start ?? min}
        max={max}
        locale={locale}
        weekStartsOn={weekStartsOn}
        disabled={disabled}
        inputProps={{ 'aria-label': endLabel }}
        onChange={(d) => setRange([start, d])}
      />
    </div>
  );
});
